version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt/live/reviseminder.com:/etc/letsencrypt/live/reviseminder.com:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
volumes:
  pgdata: