CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	qnt_studies_added INT NOT NULL DEFAULT 0,
	qnt_reviews_done INT NOT NULL DEFAULT 0,
	consented_terms BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS studies (
	id SERIAL PRIMARY KEY,
	topic VARCHAR(255) NOT NULL,
	qnt_reviews INT NOT NULL CHECK (qnt_reviews BETWEEN 0 AND 10),
	date DATE NOT NULL,
	user_id INT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
	id SERIAL PRIMARY KEY,
	topic VARCHAR(255) NOT NULL,
	status VARCHAR(255) NOT NULL,
	date DATE NOT NULL,
	study_id INT REFERENCES studies(id) ON DELETE CASCADE,
	user_id INT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS achievements (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	reward VARCHAR(255) NOT NULL,
	user_id INT REFERENCES users(id) ON DELETE CASCADE
)